ERROR || 2020-08-10 17:05:03,887 || log || Internal Server Error: /user-resources/operations-history/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\generic\base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django_filters\rest_framework\backends.py", line 96, in filter_queryset
    return filterset.qs
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django_filters\filterset.py", line 243, in qs
    qs = self.filter_queryset(qs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django_filters\filterset.py", line 230, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django_filters\filters.py", line 761, in __call__
    return self.method(qs, self.f.field_name, value)
  File "C:\Users\hardcase1\PycharmProjects\series\users\filters.py", line 125, in get_last_x_operations
    pk_to_rank = queryset.annotate(rank=Window(
TypeError: __init__() got an unexpected keyword argument 'filterable'
ERROR || 2020-08-10 17:05:04,105 || basehttp || "GET /user-resources/operations-history/?access_time__gte=&access_time__lte=&last_operations=&last_x_operations=4&model=tvseriesmodel&model=seasonmodel&model=imagemodel&ordering=content_type__model HTTP/1.1" 500 158227
ERROR || 2020-08-10 17:30:40,212 || log || Internal Server Error: /user-resources/operations-history/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\generic\base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django_filters\rest_framework\backends.py", line 96, in filter_queryset
    return filterset.qs
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django_filters\filterset.py", line 243, in qs
    qs = self.filter_queryset(qs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django_filters\filterset.py", line 230, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django_filters\filters.py", line 761, in __call__
    return self.method(qs, self.f.field_name, value)
  File "C:\Users\hardcase1\PycharmProjects\series\users\filters.py", line 125, in get_last_x_operations
    pk_to_rank = Subquery(queryset.annotate(rank=Window(
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\sql\query.py", line 1261, in build_filter
    self.check_filterable(reffed_expression)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\sql\query.py", line 1130, in check_filterable
    raise NotSupportedError(
django.db.utils.NotSupportedError: Window is disallowed in the filter clause.
ERROR || 2020-08-10 17:30:40,536 || basehttp || "GET /user-resources/operations-history/?access_time__gte=&access_time__lte=&model=tvseriesmodel&model=seasonmodel&model=imagemodel&last_operations=&last_x_operations=4 HTTP/1.1" 500 196214
ERROR || 2020-08-10 17:38:00,414 || log || Internal Server Error: /user-resources/operations-history/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\generic\base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django_filters\rest_framework\backends.py", line 96, in filter_queryset
    return filterset.qs
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django_filters\filterset.py", line 243, in qs
    qs = self.filter_queryset(qs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django_filters\filterset.py", line 230, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django_filters\filters.py", line 761, in __call__
    return self.method(qs, self.f.field_name, value)
  File "C:\Users\hardcase1\PycharmProjects\series\users\filters.py", line 125, in get_last_x_operations
    pk_to_rank = queryset.annotate(rank=Window(
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\sql\query.py", line 1261, in build_filter
    self.check_filterable(reffed_expression)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\sql\query.py", line 1136, in check_filterable
    self.check_filterable(expr)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\sql\query.py", line 1136, in check_filterable
    self.check_filterable(expr)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\sql\query.py", line 1136, in check_filterable
    self.check_filterable(expr)
  [Previous line repeated 1 more time]
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\sql\query.py", line 1130, in check_filterable
    raise NotSupportedError(
django.db.utils.NotSupportedError: Window is disallowed in the filter clause.
ERROR || 2020-08-10 17:38:00,757 || basehttp || "GET /user-resources/operations-history/?access_time__gte=&access_time__lte=&model=tvseriesmodel&model=seasonmodel&model=imagemodel&last_operations=&last_x_operations=4 HTTP/1.1" 500 212682
ERROR || 2020-08-10 17:53:29,443 || log || Internal Server Error: /user-resources/operations-history/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\generic\base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django_filters\rest_framework\backends.py", line 96, in filter_queryset
    return filterset.qs
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django_filters\filterset.py", line 243, in qs
    qs = self.filter_queryset(qs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django_filters\filterset.py", line 230, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django_filters\filters.py", line 761, in __call__
    return self.method(qs, self.f.field_name, value)
  File "C:\Users\hardcase1\PycharmProjects\series\users\filters.py", line 125, in get_last_x_operations
    pk_to_rank = queryset.annotate(rank=ExpressionWrapper(Window(
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\sql\query.py", line 1261, in build_filter
    self.check_filterable(reffed_expression)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\sql\query.py", line 1136, in check_filterable
    self.check_filterable(expr)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\db\models\sql\query.py", line 1130, in check_filterable
    raise NotSupportedError(
django.db.utils.NotSupportedError: Window is disallowed in the filter clause.
ERROR || 2020-08-10 17:53:29,774 || basehttp || "GET /user-resources/operations-history/?access_time__gte=&access_time__lte=&model=tvseriesmodel&model=seasonmodel&model=imagemodel&last_operations=&last_x_operations=4 HTTP/1.1" 500 200349
